_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 75
learning_rate:
    value: 1e-06
model:
    value: dinovit_internal_split
